adding suspender

diff --git a/edge b/edge
--- a/edge
+++ b/edge
@@ -7,7 +7,7 @@ if test -z "$1"  || test -z "$2"  || test -z "$3"; then
 help
 fi
 
-if test "$1" != "add" && test "$1" != "delete" || (test "$2" != "tariff" && test "$2" != "customer"); then
+if test "$1" != "add" && test "$1" != "delete" || (test "$2" != "tariff" && test "$2" != "customer" && test "$2" != "suspend"); then
 help
 fi
 
@@ -16,6 +16,14 @@ if test "$2" = "customer" && ! valid_ip $4; then
 
 echo "Invalid IP address $4 for tariff plan $3"
 echo "If you want tariff plan to be $3 $4 use quotes: \"$3 $4\""
+exit 1
+
+fi
+
+
+if test "$2" = "suspend" && ! valid_ip $3; then
+
+echo "Invalid IP address $3 to suspend"
 exit 1
 
 fi
@@ -35,6 +43,13 @@ if test "$2" = "tariff" && test "$1" = "delete" && ! test -z "$4"  ; then
 echo -e "\ntoo many arguments entered\n"
 exit 1
 fi
+
+if test "$2" = "suspend" && ! test -z "$4"  ; then
+echo -e "\ntoo many arguments entered\n"
+exit 1
+fi
+
+
 description=$3
 tmp=$(echo ${description// /_})
 description=$tmp
@@ -50,9 +65,10 @@ echo -e $description '\n'$4 $5 > input.txt
 user=admin
 ip=192.168.168.1
 key=./key
+port=22
 file="configure.vbash setup.vbash Data tmp input.txt"
-scp -i $key -r $file $user@$ip:~
-ssh -q $user@$ip -i $key vbash setup.vbash
-ssh -q $user@$ip -i $key rm $file
+scp -P $port -i $key -r $file $user@$ip:~
+ssh -p $port -q $user@$ip -i $key vbash setup.vbash
+ssh -p $port -q $user@$ip -i $key rm $file
 rm configure.vbash
 
